"""empty message

Revision ID: 124a33b54b1b
Revises: b0919d5d5165
Create Date: 2023-04-19 17:26:26.377830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124a33b54b1b'
down_revision = 'b0919d5d5165'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviegoers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_tickets',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('moviegoer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_tickets_movie_id_movies')),
    sa.ForeignKeyConstraint(['moviegoer_id'], ['moviegoers.id'], name=op.f('fk_movie_tickets_moviegoer_id_moviegoers')),
    sa.PrimaryKeyConstraint('movie_id', 'moviegoer_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name=op.f('fk_roles_actor_id_actors')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_roles_movie_id_movies')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('movie_tickets')
    op.drop_table('movies')
    op.drop_table('moviegoers')
    op.drop_table('actors')
    # ### end Alembic commands ###
